# [HuggingFace](https://huggingface.co/) 
<img src="https://huggingface.co/front/assets/huggingface_logo-noborder.svg">

- Repository for mainly Transformer-based models
- Comes with a high-level python API

In [ ]:
!pip install transformers

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.1/7.1 MB 71.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 224.5/224.5 kB 15.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.8/7.8 MB 42.4 MB/s eta 0:00:00


In [ ]:
from transformers import AutoTokenizer, AutoModelForCausalLM

In [ ]:
tokenizer = AutoTokenizer.from_pretrained("distilgpt2")
model = AutoModelForCausalLM.from_pretrained("distilgpt2", pad_token_id = tokenizer.eos_token_id)

In [ ]:
text = "Summer is"
tokenizer.pad_token = tokenizer.eos_token
tokens = tokenizer(text, return_tensors="pt")
tokens

{'input_ids': tensor([[33560,   318]]), 'attention_mask': tensor([[1, 1]])}

In [ ]:
completion = model.generate(tokens["input_ids"], max_length=64, do_sample=True, temperature=0.5, top_p=1.0)

/usr/local/lib/python3.10/dist-packages/transformers/generation/utils.py:1255: UserWarning: You have modified the pretrained model configuration to control generation. This is a deprecated strategy to control generation and will be removed soon, in a future version. Please use a generation configuration file (see https://huggingface.co/docs/transformers/main_classes/text_generation)
  warnings.warn(


In [ ]:
print(completion)

tensor([[33560,   318,   257,   845,  2968, 11984,  2168,   290,   257,  2168,
          9593,  1811,  1180,  3435,    13,   198,   198,   198,   198,   198,
           198,   198,   198,   198,   198,   198,   198,   198,   198,   198,
           198,   198,   198,   198,   198,   198,   198,   198,   198,   198,
           198,   198,   198,   198,   198,   198,   198,   198,   198,   198,
           198,   198,   198,   198,   198,   198,   198,   198,   198,   198,
           198,   198,   198,   198]])


In [ ]:
tokenizer.decode(completion[0])

'Summer is a very popular anime series and a series featuring several different characters.\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n'

In [ ]:
lftoken = tokenizer.encode("\n")[0]

In [ ]:
for i in range(10):
  text = "Summer is"
  tokens = tokenizer(text, return_tensors="pt")

  completion = model.generate(tokens["input_ids"], max_length=64, do_sample=True, temperature=0.5, top_p=1.0, eos_token_id=lftoken)
  print(tokenizer.decode(completion[0]))

Summer is a very well-established, well-established, well-established, well-established, well-established, well-established, well-established, well-established, well-established, well-established, well-established, well-established, well-established, well-established, well-established,
Summer is an excellent example of how we can work together to improve the lives of people who are struggling with substance abuse.

Summer is a very well-known, very unique game that is a very well-known, very unique game that is a very well-known, very unique game that is a very well-known, very unique game that is a very well-known, very unique game that is a very well-known, very
Summer is an open source project that is designed to help people build and maintain their own web application. The project is open source, and it will work on the server side of the project, and is open source.

Summer is a popular music video game for the PlayStation 4 and Xbox One. It is also a popular video game for the Pl

In [ ]:
%%time
for i in range(10):
  text = "Bob went to the cinema"
  tokens = tokenizer(text, return_tensors="pt")

  completion = model.generate(tokens["input_ids"], max_length=64, do_sample=True, temperature=0.2, top_p=1.0, eos_token_id=lftoken, repetition_penalty=1e2)
  print(tokenizer.decode(completion[0]))

Bob went to the cinema and saw a lot of people who were there, but I think that's what happened.

Bob went to the cinema and saw a movie. I was like, 'Oh my God! This is what you're doing!' And he said: "I'm not going anywhere."

Bob went to the cinema and saw a lot of people who were going through this.

Bob went to the cinema and saw a lot of people. I think it was very interesting that he had this idea for me, but also because there were so many other things in life which we could do with him."

Bob went to the cinema and found a movie.

Bob went to the cinema and saw a movie called “The Last Man on Earth”. He said, "I think it was an amazing film."

Bob went to the cinema and saw a lot of people.

Bob went to the cinema and saw a movie, but he didn't see it. He was just sitting there watching this film with his wife who had been in her car for some time now because she thought that would be funny."

Bob went to the cinema, and he was a bit surprised.

Bob went to the cinema and saw

In [ ]:
for i in range(10):
  text = "I\'ve just seen a movie which was about a robot fighting in a city. The genre of the film is Action\n"+\
          "I\'ve just seen a movie which was about English lords arguing. The genre of the film is Drama\n"+\
          "I\'ve just seen a movie which was about the Wild West and bandits. The genre of the film is"
  tokens = tokenizer(text, return_tensors="pt")

  completion = model.generate(tokens["input_ids"], max_new_tokens=3, do_sample=True, temperature=0.05, top_p=1.0, eos_token_id=lftoken, repetition_penalty=1e2)
  print(tokenizer.decode(completion[0]))

I've just seen a movie which was about a robot fighting in a city. The genre of the film is Action
I've just seen a movie which was about English lords arguing. The genre of the film is Drama
I've just seen a movie which was about the Wild West and bandits. The genre of the film is Comedy<|endoftext|>The
I've just seen a movie which was about a robot fighting in a city. The genre of the film is Action
I've just seen a movie which was about English lords arguing. The genre of the film is Drama
I've just seen a movie which was about the Wild West and bandits. The genre of the film is Comedy<|endoftext|>The
I've just seen a movie which was about a robot fighting in a city. The genre of the film is Action
I've just seen a movie which was about English lords arguing. The genre of the film is Drama
I've just seen a movie which was about the Wild West and bandits. The genre of the film is Comedy<|endoftext|>The
I've just seen a movie which was about a robot fighting in a city. The genre of th

In [ ]:
%%time
#Batched version

text = ["Bob went to the cinema"]*10
tokens = tokenizer(text, return_tensors="pt")

completion = model.generate(tokens["input_ids"], max_length=64, do_sample=True, temperature=0.2, top_p=1.0, eos_token_id=lftoken, repetition_penalty=1e2)
for i in range(10):
  print(tokenizer.decode(completion[i]).replace("<|endoftext|>",""))

Bob went to the cinema and saw a bunch of people who were there, but they didn't know what was going on.

Bob went to the cinema and saw a movie called The Last Man on screen. He was very impressed with it, but he didn't like what I said about him or anything else that could be construed as an endorsement of his views."

Bob went to the cinema and saw a movie that was about an old man who had been murdered. He said he thought it would be funny, but then suddenly there were people saying 'I'm not going anywhere'. And I think they're right - we've got no idea what's happening here."

Bob went to the cinema and saw a movie, but he didn't see it. He was just looking at his own life."

Bob went to the cinema and saw a young man who was wearing his own shirt.

Bob went to the cinema and saw a movie, but it was not.

Bob went to the cinema and saw a lot of people. I think it was great for him, but also he had his own way in life."Theresource is now on sale at auction!

Bob went to the cinema 

# Models are reusable and retrainable

## Using BERT for NER tagging

### BERT
<img src="https://1.bp.blogspot.com/-RLAbr6kPNUo/W9is5FwUXmI/AAAAAAAADeU/5y9466Zoyoc96vqLjbruLK8i_t8qEdHnQCLcBGAs/s1600/image3.png">

- Transformer Encoder Blocks (unmasked attention)
- Two special tokens **[CLS]** and **[SEP]**
- Trained with MLM (Masked Language Modelling) and NSP (Next Sentence Prediction)

### MLM
<img src="https://jalammar.github.io/images/BERT-language-modeling-masked-lm.png" width=80%>

### NSP
<img src="https://jalammar.github.io/images/bert-next-sentence-prediction.png" width=80%>



Nice visualization page: https://jalammar.github.io/illustrated-bert/


# NER (Named Entity Recognition)

Assigning a label to each token corresponding to named entities.   
Topics vary based on use-case. Most common: GEO, ORG, PER, MISC.
### In this lab   
- geo = Geographical Entity
- org = Organization
- per = Person
- gpe = Geopolitical Entity
- tim = Time indicator
- art = Artifact
- eve = Event
- nat = Natural Phenomenon

### IBO annotation
- I: inside
- B: beginning
- O: out

For example:   
"We have been in New York this september."   
" O O O O B-GEO I-GEO O B-TIM O" (last one is for punct)

### Problem: Sub-word tokens
Example: 
- "processing" is in the vocabulary
- "parsing" is OOV, regular n-gram components are used here ["p", "ars", "ing"]
- Tags are assigned to the first sub-word token this time.
- Other sub-word tokens are labeled with padding tokens

In [ ]:
print(tokenizer.tokenize("processing"))
print(tokenizer.tokenize("parsing"))

['processing']
['p', 'ars', 'ing']


Loading NER dataset

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
def download_from_drive(link, filename):
  id = link.split("/")[-2]
  !wget --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id={id}' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id={id}" -O {"/content/"+filename} && rm -rf /tmp/cookies.txt


download_from_drive("https://drive.google.com/file/d/1c6oLXggGNS5WdD9BIJK6K9H-cNnexZfD/view?usp=sharing","NER.csv")

--2023-05-22 19:59:34--  https://docs.google.com/uc?export=download&confirm=&id=1c6oLXggGNS5WdD9BIJK6K9H-cNnexZfD
Resolving docs.google.com (docs.google.com)... 172.253.122.138, 172.253.122.102, 172.253.122.101, ...
Connecting to docs.google.com (docs.google.com)|172.253.122.138|:443... connected.
HTTP request sent, awaiting response... 303 See Other
Location: https://doc-00-1k-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/ge670jurn95l8d7c9rcsa4agus3g1nmh/1684785525000/02440328774490686871/*/1c6oLXggGNS5WdD9BIJK6K9H-cNnexZfD?e=download&uuid=5cc6e2e4-5585-4cb8-9be3-0a9de26a3e04 [following]
--2023-05-22 19:59:35--  https://doc-00-1k-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/ge670jurn95l8d7c9rcsa4agus3g1nmh/1684785525000/02440328774490686871/*/1c6oLXggGNS5WdD9BIJK6K9H-cNnexZfD?e=download&uuid=5cc6e2e4-5585-4cb8-9be3-0a9de26a3e04
Resolving doc-00-1k-docs.googleusercontent.com (doc-00-1k-docs.googleusercontent.com)... 142.251.167.1

In [ ]:
df = pd.read_csv("NER.csv",encoding="windows-1251")
df.head(200)

Sentence #           Word  POS    Tag
0     Sentence: 1      Thousands  NNS      O
1             NaN             of   IN      O
2             NaN  demonstrators  NNS      O
3             NaN           have  VBP      O
4             NaN        marched  VBN      O
..            ...            ...  ...    ...
195           NaN              .    .      O
196  Sentence: 10        Iranian   JJ  B-gpe
197           NaN      officials  NNS      O
198           NaN            say  VBP      O
199           NaN           they  PRP      O

[200 rows x 4 columns]

In [ ]:
df["Tag"].value_counts()

O        887908
B-geo     37644
B-tim     20333
B-org     20143
I-per     17251
B-per     16990
I-org     16784
B-gpe     15870
I-geo      7414
I-tim      6528
B-art       402
B-eve       308
I-art       297
I-eve       253
B-nat       201
I-gpe       198
I-nat        51
Name: Tag, dtype: int64

Imbalanced dataset, we will have to deal with that later.

Creating NER <--> class id mapping

In [ ]:
id_to_ner = dict(enumerate(df["Tag"].unique()))

In [ ]:
id_to_ner

{0: 'O',
 1: 'B-geo',
 2: 'B-gpe',
 3: 'B-per',
 4: 'I-geo',
 5: 'B-org',
 6: 'I-org',
 7: 'B-tim',
 8: 'B-art',
 9: 'I-art',
 10: 'I-per',
 11: 'I-gpe',
 12: 'I-tim',
 13: 'B-nat',
 14: 'B-eve',
 15: 'I-eve',
 16: 'I-nat'}

In [ ]:
id_to_ner[-100]="[PAD]"

In [ ]:
ner_to_id = {v: k for k, v in id_to_ner.items()}
ner_to_id

{'O': 0,
 'B-geo': 1,
 'B-gpe': 2,
 'B-per': 3,
 'I-geo': 4,
 'B-org': 5,
 'I-org': 6,
 'B-tim': 7,
 'B-art': 8,
 'I-art': 9,
 'I-per': 10,
 'I-gpe': 11,
 'I-tim': 12,
 'B-nat': 13,
 'B-eve': 14,
 'I-eve': 15,
 'I-nat': 16,
 '[PAD]': -100}

Convert to sentence-based dataset.

Forwardfilling NaN values will fill missing sentence labels until a new one is met

In [ ]:
df = df.fillna(method="ffill")
df

Sentence #           Word  POS Tag
0            Sentence: 1      Thousands  NNS   O
1            Sentence: 1             of   IN   O
2            Sentence: 1  demonstrators  NNS   O
3            Sentence: 1           have  VBP   O
4            Sentence: 1        marched  VBN   O
...                  ...            ...  ...  ..
1048570  Sentence: 47959           they  PRP   O
1048571  Sentence: 47959      responded  VBD   O
1048572  Sentence: 47959             to   TO   O
1048573  Sentence: 47959            the   DT   O
1048574  Sentence: 47959         attack   NN   O

[1048575 rows x 4 columns]

Group words and NER tags by sentences and drop the duplicate rows

In [ ]:
sdf = df[["Word","Tag"]].groupby(df["Sentence #"]).transform(lambda x: " ".join(x))
sdf

Word  \
0        Thousands of demonstrators have marched throug...   
1        Thousands of demonstrators have marched throug...   
2        Thousands of demonstrators have marched throug...   
3        Thousands of demonstrators have marched throug...   
4        Thousands of demonstrators have marched throug...   
...                                                    ...   
1048570    Indian forces said they responded to the attack   
1048571    Indian forces said they responded to the attack   
1048572    Indian forces said they responded to the attack   
1048573    Indian forces said they responded to the attack   
1048574    Indian forces said they responded to the attack   

                                                       Tag  
0        O O O O O O B-geo O O O O O B-geo O O O O O B-...  
1        O O O O O O B-geo O O O O O B-geo O O O O O B-...  
2        O O O O O O B-geo O O O O O B-geo O O O O O B-...  
3        O O O O O O B-geo O O O O O B-geo O O O O O B-...  
4        O O O O O O B-geo O O O O O B-geo O O O O O B-...  
...                                                    ...  
1048570                                B-gpe O O O O O O O  
1048571                                B-gpe O O O O O O O  
1048572                                B-gpe O O O O O O O  
1048573                                B-gpe O O O O O O O  
1048574                                B-gpe O O O O O O O  

[1048575 rows x 2 columns]

In [ ]:
sdf = sdf.drop_duplicates()
sdf

Word  \
0        Thousands of demonstrators have marched throug...   
24       Families of soldiers killed in the conflict jo...   
54       They marched from the Houses of Parliament to ...   
68       Police put the number of marchers at 10,000 wh...   
83       The protest comes on the eve of the annual con...   
...                                                    ...   
1048501  Indian border security forces are accusing the...   
1048521  Indian officials said no one was injured in Sa...   
1048545  Two more landed in fields belonging to a nearb...   
1048556  They say not all of the rockets exploded upon ...   
1048567    Indian forces said they responded to the attack   

                                                       Tag  
0        O O O O O O B-geo O O O O O B-geo O O O O O B-...  
24       O O O O O O O O O O O O O O O O O O B-per O O ...  
54                     O O O O O O O O O O O B-geo I-geo O  
68                           O O O O O O O O O O O O O O O  
83       O O O O O O O O O O O B-geo O O B-org I-org O ...  
...                                                    ...  
1048501  B-gpe O O O O O O B-gpe O O O O O O O O O B-ge...  
1048521  B-gpe O O O O O O O B-tim O O O O O O O O O O ...  
1048545                              O O O O O O O O O O O  
1048556                              O O O O O O O O O O O  
1048567                                B-gpe O O O O O O O  

[47610 rows x 2 columns]

Resetting indices for better handling (optional)

In [ ]:
sdf = sdf.reset_index(drop=True)
sdf

Word  \
0      Thousands of demonstrators have marched throug...   
1      Families of soldiers killed in the conflict jo...   
2      They marched from the Houses of Parliament to ...   
3      Police put the number of marchers at 10,000 wh...   
4      The protest comes on the eve of the annual con...   
...                                                  ...   
47605  Indian border security forces are accusing the...   
47606  Indian officials said no one was injured in Sa...   
47607  Two more landed in fields belonging to a nearb...   
47608  They say not all of the rockets exploded upon ...   
47609    Indian forces said they responded to the attack   

                                                     Tag  
0      O O O O O O B-geo O O O O O B-geo O O O O O B-...  
1      O O O O O O O O O O O O O O O O O O B-per O O ...  
2                    O O O O O O O O O O O B-geo I-geo O  
3                          O O O O O O O O O O O O O O O  
4      O O O O O O O O O O O B-geo O O B-org I-org O ...  
...                                                  ...  
47605  B-gpe O O O O O O B-gpe O O O O O O O O O B-ge...  
47606  B-gpe O O O O O O O B-tim O O O O O O O O O O ...  
47607                              O O O O O O O O O O O  
47608                              O O O O O O O O O O O  
47609                                B-gpe O O O O O O O  

[47610 rows x 2 columns]

Load BertTokenizerFast for tokenization and TFBertForTokenClassification (TF means tensorflow compatibility here)

In [ ]:
from transformers import BertTokenizerFast, TFBertForTokenClassification

Use the cased version, as upper-case is a clue for a large number of entities

In [ ]:
tokenizer = BertTokenizerFast.from_pretrained("bert-base-cased")

Subword tokens are present, only the leading tokens should get a NER tag each word.

In [ ]:
text = sdf["Word"][7]
tokenizer.tokenize(text)

['The',
 'International',
 'Atomic',
 'Energy',
 'Agency',
 'is',
 'to',
 'hold',
 'second',
 'day',
 'of',
 'talks',
 'in',
 'Vienna',
 'Wednesday',
 'on',
 'how',
 'to',
 'respond',
 'to',
 'Iran',
 "'",
 's',
 're',
 '##sumption',
 'of',
 'low',
 '-',
 'level',
 'uranium',
 'conversion',
 '.']

In [ ]:
tokenizer(text.split(" "), is_split_into_words=True, add_special_tokens=True, 
          max_length=64, padding="max_length", return_attention_mask=True, 
          return_offsets_mapping=True)
  

{'input_ids': [101, 1109, 1570, 18662, 5514, 5571, 1110, 1106, 2080, 1248, 1285, 1104, 7430, 1107, 5337, 9031, 1113, 1293, 1106, 6297, 1106, 3398, 112, 188, 1231, 16937, 1104, 1822, 118, 1634, 16410, 7497, 119, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'token_type_ids': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'offset_mapping': [(0, 0), (0, 3), (0, 13), (0, 6), (0, 6), (0, 6), (0, 2), (0, 2), (0, 4), (0, 6), (0, 3), (0, 2), (0, 5), (0, 2), (0, 6), (0, 9), (0, 2), (0, 3), (0, 2), (0, 7), (0, 2), (0, 4), (0, 1), (1, 2), (0, 2), (2, 10), (0, 2), (0, 3), (3, 4), (4, 9), (0, 7), 

In [ ]:
import tensorflow as tf

Assembling sequences.   
[PAD] and non-leading subword tokens are denoted with NER token ID -100

In [ ]:
def prepare_training_data(text, ner=None):
  ids, _, att, off = tokenizer(text.split(" "), is_split_into_words=True, add_special_tokens=True, 
                            max_length=64, padding="max_length", truncation=True, return_attention_mask=True, 
                            return_offsets_mapping=True).values()
  ids = np.array(ids)
  att = np.array(att)
  label = np.ones_like(ids, dtype=np.int32)*-100
  if ner is not None:
    for i, offset in enumerate(off):
      if offset[0]==0 and offset[1]!=0:
        label[i] = ner_to_id[ner.pop(0)]
  
  return ids, att, label

In [ ]:
prepare_training_data("This is a test sentence",["O","O","O","B-geo","O"])

(array([ 101, 1188, 1110,  170, 2774, 5650,  102,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0]),
 array([1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([-100,    0,    0,    0,    1,    0, -100, -100, -100, -100, -100,
        -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100,
        -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100,
        -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100,
        -100, -100, -100, -100, -100, -100, -100, -1

In [ ]:
prepare_training_data("This is a teszt sentence",["O","O","O","B-geo","O"])

(array([  101,  1188,  1110,   170, 21359, 21529,  1204,  5650,   102,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0]),
 array([1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([-100,    0,    0,    0,    1, -100, -100,    0, -100, -100, -100,
        -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100,
        -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100,
        -100, -100, -100, -100, -100, -100, -1

In [ ]:
def prepare_df(series):
  series["ids"], series["att"], series["label"] = prepare_training_data(series["Word"],series["Tag"].split(" "))
  return series

In [ ]:
sdf=sdf.apply(prepare_df,axis=1)
sdf.head()

Word  \
0  Thousands of demonstrators have marched throug...   
1  Families of soldiers killed in the conflict jo...   
2  They marched from the Houses of Parliament to ...   
3  Police put the number of marchers at 10,000 wh...   
4  The protest comes on the eve of the annual con...   

                                                 Tag  \
0  O O O O O O B-geo O O O O O B-geo O O O O O B-...   
1  O O O O O O O O O O O O O O O O O O B-per O O ...   
2                O O O O O O O O O O O B-geo I-geo O   
3                      O O O O O O O O O O O O O O O   
4  O O O O O O O O O O O B-geo O O B-org I-org O ...   

                                                 ids  \
0  [101, 26159, 1104, 8568, 4487, 5067, 1138, 963...   
1  [101, 21860, 1104, 2803, 1841, 1107, 1103, 413...   
2  [101, 1220, 9639, 1121, 1103, 16862, 1104, 290...   
3  [101, 3284, 1508, 1103, 1295, 1104, 8943, 1468...   
4  [101, 1109, 5641, 2502, 1113, 1103, 23491, 110...   

                                                 att  \
0  [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...   
1  [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...   
2  [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...   
3  [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...   
4  [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...   

                                               label  
0  [-100, 0, 0, 0, -100, -100, 0, 0, 0, 1, 0, 0, ...  
1  [-100, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
2  [-100, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 4, ...  
3  [-100, 0, 0, 0, 0, 0, 0, -100, 0, 0, -100, -10...  
4  [-100, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, ...

Splitting df into datasets for training, validation and testing

In [ ]:
ids_train, ids_val, ids_test = np.split(sdf["ids"].sample(frac=1, random_state=1), [int(0.6*len(sdf)), int(0.8*len(sdf))])
att_train, att_val, att_test = np.split(sdf["att"].sample(frac=1, random_state=1), [int(0.6*len(sdf)), int(0.8*len(sdf))])
Y_train, Y_val, Y_test = np.split(sdf["label"].sample(frac=1, random_state=1), [int(0.6*len(sdf)), int(0.8*len(sdf))])

print(ids_train, end="\n\n")
print(ids_train.to_numpy())

29322    [101, 5459, 117, 1107, 14465, 117, 5229, 1104,...
42836    [101, 1109, 19342, 1138, 4963, 1106, 4010, 497...
13609    [101, 1109, 2061, 1585, 1110, 26943, 1158, 112...
11034    [101, 1109, 4711, 2084, 112, 188, 7430, 1114, ...
6405     [101, 1109, 1291, 3225, 6534, 10777, 1199, 122...
                               ...                        
25575    [101, 1448, 4229, 3300, 1867, 1103, 8602, 1108...
32856    [101, 1109, 2084, 1110, 1103, 1148, 1809, 2301...
24946    [101, 1109, 1244, 3854, 1867, 1120, 1655, 1955...
17090    [101, 9578, 112, 188, 2084, 1144, 9497, 10299,...
5859     [101, 2677, 1104, 1103, 1300, 12555, 1132, 635...
Name: ids, Length: 28566, dtype: object

[array([  101,  5459,   117,  1107, 14465,   117,  5229,  1104,  6638,
         1104,  8276, 14104,   112,  1122,  1162,   172,  2879,  1596,
        12556,  4426, 18518,  1161,  2393,   118, 20572,  1197,  7160,
         1222,  3675,  1111,  2877,  1863,  1107,  5008,   119,   102,
            0,     0,     

Convert the series of numpy arrays into a single array

In [ ]:
def conv_np_stack(series):
  return np.vstack(series.to_numpy())

In [ ]:
X_train = (conv_np_stack(ids_train), conv_np_stack(att_train))
X_val = (conv_np_stack(ids_val), conv_np_stack(att_val))
X_test = (conv_np_stack(ids_test), conv_np_stack(att_test))

Y_train = np.vstack(Y_train)
Y_val = np.vstack(Y_val)
Y_test = np.vstack(Y_test)

print(X_train[0].shape)

(28566, 64)


Highly imbalanced dataset, let's assign class weights for loss calculation   
(i.e.: the O class will have a low loss, the less frequent classes have high losses)

In [ ]:
from sklearn.utils import class_weight

class_weights = class_weight.compute_class_weight('balanced',classes=np.unique(Y_train[np.bitwise_and(Y_train!=-100,Y_train!=0)]), y=Y_train[np.bitwise_and(Y_train!=-100,Y_train!=0)])
class_weights = list(class_weights)
class_weights.insert(0,1)
class_weights = np.array(class_weights)
class_weights

array([  1.        ,   0.26942918,   0.6332406 ,   0.58805323,
         1.37346311,   0.50143392,   0.59174514,   0.49114558,
        24.92665289,  31.25518135,   0.57713835,  51.12076271,
         1.52175832,  46.76162791,  34.27414773,  44.0310219 ,
       177.41911765])

In [ ]:
#sqrt for less agressive corrections
class_weights = tf.convert_to_tensor(class_weights**(1/2))
class_weights

<tf.Tensor: shape=(17,), dtype=float64, numpy=
array([ 1.        ,  0.51906568,  0.79576416,  0.76684629,  1.17194843,
        0.70811999,  0.76924973,  0.70081779,  4.9926599 ,  5.59063336,
        0.75969622,  7.14987851,  1.23359569,  6.83824743,  5.85441267,
        6.63558753, 13.31987679])>

### Custom Loss Function

1. Use categorical crossentropy as base
  - Sparse: The labels are specified as class IDs, not as vectors
  - From logits (False): We did use softmax
2. The NER token for PAD causes an error (there is no -100th element)
  - Replace it with meaningful values (0 in this example)
  - Mask the loss values (multiply by 0) coming from these tokens (as they are irrelevant)
3. Apply class weights from above
  - tf.gather() gathers all the weights specified by the tokenID values

### Custom Accuracy Functions
1. acc_all is the non-[PAD] token accuracy
2. acc_NER is the non-[PAD], non-O token accuracy

In [ ]:
@tf.function
def loss_function(y_true, y_pred):
  others = tf.equal(y_true, 0) # NER TAG: O
  pads = tf.equal(y_true, -100) # NER TAG: [PAD]
  rand_leave_negative_examples = tf.math.greater(tf.random.uniform(tf.shape(pads)),0.03)

  #NOT(PAD | (O_tags & should be left out))
  mask = tf.logical_not(tf.math.logical_or(pads, tf.logical_and(rand_leave_negative_examples,others)))
  
  y_nopad = tf.where(pads,0,y_true)
  
  loss = tf.keras.losses.sparse_categorical_crossentropy(y_nopad, y_pred, from_logits=False)
  loss *= tf.cast(mask, loss.dtype)
  class_weight = tf.cast(tf.gather(class_weights,y_nopad), loss.dtype)
  loss *= class_weight
  return tf.reduce_sum(loss)/(tf.reduce_sum(tf.cast(mask, loss.dtype))+1e-8)

@tf.function
def acc_all(real, pred):
    pads = tf.math.equal(real, -100)
    mask = tf.math.logical_not(pads)
    
    acc = tf.equal(real+100*tf.cast(pads, dtype=real.dtype), tf.cast(tf.argmax(pred, axis=-1),dtype=real.dtype))
    acc = tf.cast(tf.logical_and(acc,mask), dtype=tf.float32)

    return tf.reduce_sum(acc)/(tf.reduce_sum(tf.cast(mask,dtype=tf.float32))+1e-8)

@tf.function
def acc_NER(real, pred):
    ignored = tf.logical_or(tf.math.equal(real, -100), tf.math.equal(real, 0))
    mask = tf.math.logical_not(ignored)
    
    acc = tf.equal(real+100*tf.cast(ignored, dtype=real.dtype), tf.cast(tf.argmax(pred, axis=-1),dtype=real.dtype))
    acc = tf.cast(tf.logical_and(acc,mask),dtype=tf.float32)

    return tf.reduce_sum(acc)/(tf.reduce_sum(tf.cast(mask,dtype=tf.float32))+1e-8)


Load model, specify the number of outputs (PAD is not needed)

In [ ]:
model = TFBertForTokenClassification.from_pretrained("bert-base-cased", num_labels=len(ner_to_id)-1)

All model checkpoint layers were used when initializing TFBertForTokenClassification.

Some layers of TFBertForTokenClassification were not initialized from the model checkpoint at bert-base-cased and are newly initialized: ['classifier']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


Using softmax as the last layer activation for proper classification   
(from_logits=True in loss calculation is fine too)


In [ ]:
model.classifier.activation=tf.keras.activations.softmax

Pretraining the classifier only

In [ ]:
model.bert.trainable=False
model.classifier.trainable=True

In [ ]:
model.compile(loss=loss_function, optimizer=tf.keras.optimizers.Adam(learning_rate=5e-5), metrics=[acc_NER,acc_all])

In [ ]:
model.fit(X_train,Y_train,validation_data=(X_val,Y_val),batch_size=64,epochs=2)

Epoch 1/2
447/447 [==============================] - 230s 473ms/step - loss: 1.8576 - acc_NER: 0.3942 - acc_all: 0.6979 - val_loss: 1.5242 - val_acc_NER: 0.5655 - val_acc_all: 0.8756
Epoch 2/2
447/447 [==============================] - 170s 381ms/step - loss: 1.3858 - acc_NER: 0.6288 - acc_all: 0.8735 - val_loss: 1.2097 - val_acc_NER: 0.6815 - val_acc_all: 0.8897


Fine-tuning the whole architecture

In [ ]:
model.bert.trainable=True
model.classifier.trainable=True

In [ ]:
model.compile(loss=loss_function, optimizer=tf.keras.optimizers.Adam(learning_rate=1e-5), metrics=[acc_NER,acc_all])

In [ ]:
model.fit(X_train,Y_train,validation_data=(X_val,Y_val),batch_size=32,epochs=100)

Epoch 1/100
893/893 [==============================] - 513s 515ms/step - loss: 0.5364 - acc_NER: 0.8176 - acc_all: 0.9244 - val_loss: 0.3980 - val_acc_NER: 0.8533 - val_acc_all: 0.9451
Epoch 2/100
893/893 [==============================] - 449s 503ms/step - loss: 0.3520 - acc_NER: 0.8599 - acc_all: 0.9394 - val_loss: 0.3619 - val_acc_NER: 0.8566 - val_acc_all: 0.9477
Epoch 3/100
463/893 [==============>...............] - ETA: 2:55 - loss: 0.2881 - acc_NER: 0.8763 - acc_all: 0.9473

KeyboardInterrupt: ignored

<img src="https://i.ytimg.com/vi/2CyP3hAOy0g/maxresdefault.jpg" width=50%>

In [ ]:
def download_from_drive(link, filename):
  id = link.split("/")[-2]
  !wget --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id={id}' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id={id}" -O {"/content/"+filename+".rar"} && rm -rf /tmp/cookies.txt
  !unrar x -Y {"/content/"+filename+".rar"} {"/content/"+filename+"/"}

download_from_drive("https://drive.google.com/file/d/1yPG7yv2z-bbMY1PS6dVOr2YpgfZg3aBK/view?usp=sharing","checkpoints")

--2023-05-22 20:28:56--  https://docs.google.com/uc?export=download&confirm=t&id=1yPG7yv2z-bbMY1PS6dVOr2YpgfZg3aBK
Resolving docs.google.com (docs.google.com)... 172.253.115.101, 172.253.115.113, 172.253.115.138, ...
Connecting to docs.google.com (docs.google.com)|172.253.115.101|:443... connected.
HTTP request sent, awaiting response... 303 See Other
Location: https://doc-0c-1k-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/4csg9169ci783aek9d4j314rubb8i7li/1684787325000/02440328774490686871/*/1yPG7yv2z-bbMY1PS6dVOr2YpgfZg3aBK?e=download&uuid=3e41614f-6ba9-4c11-afd6-b6c5c86c57cd [following]
--2023-05-22 20:28:56--  https://doc-0c-1k-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/4csg9169ci783aek9d4j314rubb8i7li/1684787325000/02440328774490686871/*/1yPG7yv2z-bbMY1PS6dVOr2YpgfZg3aBK?e=download&uuid=3e41614f-6ba9-4c11-afd6-b6c5c86c57cd
Resolving doc-0c-1k-docs.googleusercontent.com (doc-0c-1k-docs.googleusercontent.com)... 142.251.167.

In [ ]:
model = TFBertForTokenClassification.from_pretrained("./checkpoints/NER_lab_trained")

All model checkpoint layers were used when initializing TFBertForTokenClassification.

All the layers of TFBertForTokenClassification were initialized from the model checkpoint at ./checkpoints/NER_lab_trained.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertForTokenClassification for predictions without further training.


In [ ]:
model.compile(loss=loss_function, optimizer=tf.keras.optimizers.Adam(learning_rate=1e-5), metrics=[acc_NER,acc_all])

In [ ]:
model.evaluate(X_test, Y_test)

298/298 [==============================] - 51s 144ms/step - loss: 1.2995 - acc_NER: 0.8730 - acc_all: 0.9577


[1.2995046377182007, 0.8730359077453613, 0.9576652646064758]

Making predictions using sub-word tokens

In [ ]:
def predict_entities(text):
  ids, att, _ = prepare_training_data(text)
  #(64,)-->(1, 64)
  return model.predict((np.expand_dims(ids,0),np.expand_dims(att,0)))

In [ ]:
predict_entities("This is a sentence about New York and Boston.")

1/1 [==============================] - 4s 4s/step


TFTokenClassifierOutput(loss=None, logits=array([[[ 7.394515  ,  1.836859  ,  0.2529405 , ..., -2.602069  ,
         -2.8288252 , -2.2467585 ],
        [10.4971695 ,  0.8446492 , -0.8676269 , ..., -3.836185  ,
         -3.261433  , -2.6797745 ],
        [11.0004835 ,  0.39116016, -1.0814829 , ..., -3.6836996 ,
         -3.1966357 , -2.7357965 ],
        ...,
        [ 3.3465908 ,  1.0002524 , -0.07820229, ..., -1.1290853 ,
         -1.7160007 , -1.1882938 ],
        [ 4.7629185 ,  0.6839687 , -0.22230786, ..., -1.76533   ,
         -1.9400254 , -1.4089925 ],
        [ 5.1745715 ,  0.51804453,  0.13305889, ..., -1.6604767 ,
         -1.81544   , -1.1674573 ]]], dtype=float32), hidden_states=None, attentions=None)

In [ ]:
def predict_entities(text):
  ids, att, _ = prepare_training_data(text)
  attmask = np.dstack([att]*model.num_labels)
  return model.predict((np.expand_dims(ids,0),np.expand_dims(att,0)))["logits"][attmask==1].reshape(-1,model.num_labels)
  

In [ ]:
text = "This is a sentence about New York a Boston."

ner_ids = np.argmax(predict_entities(text), axis=-1)
ner_ids

1/1 [==============================] - 0s 77ms/step


array([0, 0, 0, 0, 0, 0, 1, 4, 0, 1, 0, 0])

In [ ]:
tokens = tokenizer.tokenize(text)
ner_ids = np.argmax(predict_entities(text), axis=-1)
for i, token in enumerate(tokens,1):
  nertoken = id_to_ner[ner_ids[i]]
  print(token, nertoken)

1/1 [==============================] - 0s 83ms/step
This O
is O
a O
sentence O
about O
New B-geo
York I-geo
a O
Boston B-geo
. O


In [ ]:
def gather_entities(text):
  entities = []
  inent = False
  ent_type = None
  ent_tokens = []

  tokens = tokenizer.tokenize(text)
  ner_ids = np.argmax(predict_entities(text), axis=-1)

  for i, token in enumerate(tokens,1):
    nertoken = id_to_ner[ner_ids[i]]

    if inent:
      # Finalize entity by linking tokens together, taking care of sub-words too
      if nertoken=="O" or i == len(tokens):
        entities.append([" ".join(ent_tokens).replace(" ##",""), ent_type])
        inent = False
      elif nertoken[0]=="B" or (nertoken[0]=="I" and nertoken[2:]!=ent_type): 
        entities.append([" ".join(ent_tokens).replace(" ##",""),ent_type])
        ent_tokens = [token]
        ent_type = nertoken[2:]
      elif nertoken[0]=="I" and nertoken[2:]==ent_type:
        ent_tokens.append(token)

    else:
      if nertoken[0] in ["B","I"]:
        inent = True
        ent_tokens = [token]
        ent_type = nertoken[2:]

  return entities

In [ ]:
gather_entities("This phone was made by Apple.")

1/1 [==============================] - 0s 48ms/step


[['Apple', 'org']]

In [ ]:
gather_entities("Google Colab is a nice tool.")

1/1 [==============================] - 0s 113ms/step


[['Google Colab', 'org']]

In [ ]:
gather_entities("Bill went to the local Police Department to file a case.")

1/1 [==============================] - 0s 49ms/step


[['Bill', 'per'], ['Police Department', 'org']]

In [ ]:
gather_entities("Michael Jackson is my favorite singer.")

1/1 [==============================] - 0s 62ms/step


[['Michael Jackson', 'per']]

In [ ]:
gather_entities("Christmas Eve is my favorite time of the year.")

1/1 [==============================] - 0s 49ms/step


[['Christmas Eve', 'tim'], ['time', 'tim'], ['of', 'tim']]